export interface SampleProduct {
  _id: string;
  sku?: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  subcategory?: string;
  price: number;
  retailPrice?: number;
  discountPrice?: number;
  images: Array<{ url: string; alt?: string }>;
  stock: number;
  brand?: string;
  manufacturer?: string;
  tags?: string[];
  rating?: number;
  reviewCount?: number;
  status?: 'active' | 'inactive' | 'draft';
  isFeatured?: boolean;
  isNewArrival?: boolean;
  isBestSeller?: boolean;
  color?: string;
  size?: string;
  createdAt?: string;
}

export const sampleProducts: SampleProduct[] = [
  {
    _id: 'sample-book-1',
    sku: 'BOOK-001',
    name: 'Art & Design - Creative Expression',
    slug: 'art-design-creative-expression',
    description: 'Guide to art techniques, design principles, and creative expression with illustrations and examples.',
    category: 'books',
    price: 480,
    discountPrice: 380,
    stock: 28,
    brand: 'Radhe',
    tags: ['art', 'design', 'creativity'],
    rating: 4.4,
    reviewCount: 18,
    images: [{ url: '/pexels-photo-45717.webp', alt: 'Art & Design - Creative Expression' }],
    status: 'active',
    isFeatured: true,
    createdAt: '2024-01-12T10:00:00.000Z',
  },
  {
    _id: 'sample-book-2',
    sku: 'BOOK-002',
    name: 'Hindi Literature - Kavya Sangrah',
    slug: 'hindi-literature-kavya',
    description: 'Collection of Hindi poetry and literature from classical and contemporary authors.',
    category: 'books',
    price: 420,
    discountPrice: 340,
    stock: 38,
    brand: 'Radhe',
    tags: ['hindi', 'literature', 'poetry'],
    rating: 4.2,
    reviewCount: 12,
    images: [
      {
        url: '/glasses-resting-on-stack-of-teal-books-with-mug-in-soft-natural-light-free-photo.jpeg',
        alt: 'Hindi Literature - Kavya Sangrah',
      },
    ],
    status: 'active',
    isFeatured: true,
    createdAt: '2024-01-10T09:00:00.000Z',
  },
  {
    _id: 'sample-book-3',
    sku: 'BOOK-003',
    name: 'Economics - Principles & Practice',
    slug: 'economics-principles-practice',
    description: 'Introduction to economic principles, microeconomics, and macroeconomics with real-world examples.',
    category: 'books',
    price: 540,
    discountPrice: 440,
    stock: 32,
    brand: 'Radhe',
    tags: ['economics', 'business', 'social-science'],
    rating: 4.5,
    reviewCount: 21,
    images: [{ url: '/stack-of-books.png', alt: 'Economics - Principles & Practice' }],
    status: 'active',
    isFeatured: true,
    createdAt: '2024-01-09T08:30:00.000Z',
  },
  {
    _id: 'sample-book-4',
    sku: 'BOOK-004',
    name: 'Computer Science Basics',
    slug: 'computer-science-basics',
    description: 'Introduction to computer science, programming concepts, and digital literacy for beginners.',
    category: 'books',
    price: 495,
    discountPrice: 395,
    stock: 55,
    brand: 'Radhe',
    tags: ['computer-science', 'programming', 'technology'],
    rating: 4.6,
    reviewCount: 27,
    images: [{ url: '/download.jpeg', alt: 'Computer Science Basics' }],
    status: 'active',
    isFeatured: true,
    createdAt: '2024-01-08T08:00:00.000Z',
  },
  {
    _id: 'sample-book-5',
    sku: 'BOOK-005',
    name: 'Mathematics for Class 10',
    slug: 'mathematics-class-10',
    description: 'Comprehensive mathematics textbook covering algebra, geometry, and trigonometry for class 10 students.',
    category: 'books',
    price: 450,
    discountPrice: 380,
    stock: 50,
    brand: 'Radhe',
    tags: ['textbook', 'mathematics', 'class-10'],
    rating: 4.3,
    reviewCount: 16,
    images: [{ url: '/gettyimages-1455958786-612x612.jpg', alt: 'Mathematics for Class 10' }],
    status: 'active',
    createdAt: '2024-01-07T07:30:00.000Z',
  },
  {
    _id: 'sample-book-6',
    sku: 'BOOK-006',
    name: 'English Literature - Classics Collection',
    slug: 'english-literature-classics',
    description: 'A curated collection of classic English literature including Shakespeare, Austen, and Dickens.',
    category: 'books',
    price: 599,
    discountPrice: 499,
    stock: 35,
    brand: 'Radhe',
    tags: ['literature', 'english', 'classics'],
    rating: 4.1,
    reviewCount: 10,
    images: [
      {
        url: '/glasses-resting-on-stack-of-teal-books-with-mug-in-soft-natural-light-free-photo.jpeg',
        alt: 'English Literature Classics',
      },
    ],
    status: 'active',
    createdAt: '2024-01-06T07:00:00.000Z',
  },
  {
    _id: 'sample-book-7',
    sku: 'BOOK-007',
    name: 'Science Fundamentals - Physics & Chemistry',
    slug: 'science-fundamentals-physics-chemistry',
    description: 'Integrated science textbook covering physics and chemistry concepts for middle school students.',
    category: 'books',
    price: 520,
    discountPrice: 420,
    stock: 45,
    brand: 'Radhe',
    tags: ['science', 'physics', 'chemistry'],
    rating: 4.0,
    reviewCount: 8,
    images: [{ url: '/stack-of-books.png', alt: 'Science Fundamentals' }],
    status: 'active',
    createdAt: '2024-01-05T06:30:00.000Z',
  },
  {
    _id: 'sample-book-8',
    sku: 'BOOK-008',
    name: 'Geography - World Atlas',
    slug: 'geography-world-atlas',
    description: 'Comprehensive world atlas with maps, geographical data, and information about countries and regions.',
    category: 'books',
    price: 750,
    discountPrice: 600,
    stock: 25,
    brand: 'Radhe',
    tags: ['geography', 'atlas', 'maps'],
    rating: 4.2,
    reviewCount: 9,
    images: [{ url: '/stack-of-books.png', alt: 'Geography - World Atlas' }],
    status: 'active',
    createdAt: '2024-01-04T06:00:00.000Z',
  },
  {
    _id: 'sample-stationery-1',
    sku: 'STAT-001',
    name: 'Premium Ball Pens (Pack of 10)',
    slug: 'premium-ball-pens-pack',
    description: 'Smooth-writing ball pens with comfortable grip for everyday use.',
    category: 'stationery',
    price: 120,
    discountPrice: 99,
    stock: 120,
    brand: 'Cello',
    tags: ['pens', 'writing', 'office'],
    rating: 4.3,
    reviewCount: 34,
    images: [{ url: '/stationery.png', alt: 'Premium Ball Pens' }],
    status: 'active',
    isBestSeller: true,
    createdAt: '2024-01-03T05:30:00.000Z',
  },
  {
    _id: 'sample-stationery-2',
    sku: 'STAT-002',
    name: 'Notebooks A5 (Pack of 3)',
    slug: 'notebooks-a5-pack',
    description: 'Durable A5 notebooks with smooth pages for class notes and journaling.',
    category: 'stationery',
    price: 220,
    discountPrice: 180,
    stock: 80,
    brand: 'Classmate',
    tags: ['notebooks', 'study', 'school'],
    rating: 4.1,
    reviewCount: 22,
    images: [{ url: '/stack-of-books.png', alt: 'Notebooks A5' }],
    status: 'active',
    createdAt: '2024-01-02T05:00:00.000Z',
  },
  {
    _id: 'sample-art-1',
    sku: 'ART-001',
    name: 'Acrylic Paint Set (12 Colors)',
    slug: 'acrylic-paint-set-12',
    description: 'Rich, vibrant acrylic paints for canvas, paper, and craft projects.',
    category: 'art',
    price: 350,
    discountPrice: 299,
    stock: 60,
    brand: 'Camel',
    tags: ['paints', 'art', 'colors'],
    rating: 4.4,
    reviewCount: 19,
    images: [{ url: '/palette.png', alt: 'Acrylic Paint Set' }],
    status: 'active',
    createdAt: '2024-01-01T04:30:00.000Z',
  },
  {
    _id: 'sample-art-2',
    sku: 'ART-002',
    name: 'Sketch Pad A4 (100 Sheets)',
    slug: 'sketch-pad-a4',
    description: 'Thick, smooth sheets ideal for pencil, charcoal, and ink sketches.',
    category: 'art',
    price: 180,
    discountPrice: 150,
    stock: 90,
    brand: 'Camlin',
    tags: ['sketch', 'drawing', 'art'],
    rating: 4.2,
    reviewCount: 15,
    images: [{ url: '/paper-crafts.png', alt: 'Sketch Pad A4' }],
    status: 'active',
    createdAt: '2023-12-31T04:00:00.000Z',
  },
  {
    _id: 'sample-craft-1',
    sku: 'CRFT-001',
    name: 'Craft Paper Pack (50 Sheets)',
    slug: 'craft-paper-pack',
    description: 'Colorful craft paper sheets for school projects and DIY crafts.',
    category: 'craft',
    price: 160,
    discountPrice: 130,
    stock: 70,
    brand: 'Fevicryl',
    tags: ['craft', 'paper', 'diy'],
    rating: 4.0,
    reviewCount: 11,
    images: [{ url: '/paper-crafts.png', alt: 'Craft Paper Pack' }],
    status: 'active',
    createdAt: '2023-12-30T03:30:00.000Z',
  },
  {
    _id: 'sample-craft-2',
    sku: 'CRFT-002',
    name: 'Glue Stick Set (Pack of 3)',
    slug: 'glue-stick-set',
    description: 'Quick-dry glue sticks for school and craft use.',
    category: 'craft',
    price: 90,
    discountPrice: 75,
    stock: 110,
    brand: 'Fevicol',
    tags: ['glue', 'craft', 'school'],
    rating: 4.1,
    reviewCount: 14,
    images: [{ url: '/paper-crafts.png', alt: 'Glue Stick Set' }],
    status: 'active',
    createdAt: '2023-12-29T03:00:00.000Z',
  },
];
